trigger:
- '*'

variables:
  buildConfiguration: 'Release'

stages:
- stage: 'Deploy'
  displayName: 'Deploy the web application'
  jobs:
  - deployment: Deploy
    pool:
      vmImage: 'ubuntu-20.04'
    environment: dev
    variables:
    - group: Release
    strategy:
      runOnce:
        deploy:
          steps:
          - download: none
            artifact: drop
            
          - task: DownloadPipelineArtifact@2
            inputs:
              buildType: 'specific'
              project: 'GithubPipelineDemoHostedAgent'
              definition: 6
              buildVersionToDownload: 'latest'

          - task: AzureWebApp@1
            displayName: 'Azure App Service Deploy: website'
            inputs:
              azureSubscription: 'Resource Manager - Tailspin - Space Game'
              appName: '$(WebAppName)'
              package: '$(Pipeline.Workspace)/drop/$(buildConfiguration)/Tailspin.SpaceGame.Web.zip'